spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

server:
  port: ${PORT}
app:
  capacity:
    url: http://localhost:8084
  technology:
    url: http://localhost:8083


